<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BasicEducation extends Model
{
    use HasFactory;

    protected $fillable = [
        'lastname',
        'firstname',
        'middlename',
        'extension',
        'birthdate',
        'gender',
        'image',
        'marital_status',
        'spouse_name',
        'student_children_num',
        'is_orphan',
        'medical_condition',
        'hobby',
        'student_affiliation',
        'blood_type',
        'brothers_num',
        'sisters_num',
        'is_balik_aral',
        'is_4p_beneficiary',
        'parent_affiliation',
        'position',
        'years_of_service',
        'educational_background',
        'monthly_income',
        'source_of_income',
        'has_real_property',
        'has_personal_property',
        'has_house',
        'contact_num',
        'parent_children_num',
        'dependents_num',
        'mode_of_transport',
        'school_distance',
        'peace_condition',
        'address',
        'business_interest',
    ];
    
    // protected $fillable = [
    //     'birth_certificate_no',
    //     'learner_reference_number',
    //     'lastname',
    //     'firstname',
    //     'middlename',
    //     'extension',
    //     'birthdate',
    //     'gender',
    //     'ip_community',
    //     'mother_tongue',
    //     'house_no',
    //     'street',
    //     'baranggay',
    //     'city',
    //     'municipality',
    //     'province',
    //     'country',
    //     'zipcode',
    //     'father_lastname',
    //     'father_firstname',
    //     'father_middlename',
    //     'father_mobile',
    //     'father_phone',
    //     'mother_lastname',
    //     'mother_firstname',
    //     'mother_middlename',
    //     'mother_mobile',
    //     'mother_phone',
    //     'guardian_lastname',
    //     'guardian_firstname',
    //     'guardian_middlename',
    //     'guardian_mobile',
    //     'guardian_phone',
    //     'last_grade_level_completed',
    //     'last_school_year_completed',
    //     'school_name',
    //     'school_id',
    //     'school_address',
    //     'semester',
    //     'track',
    //     'strand',
    //     'status'
    // ];
}
